### ISSUE TITLE
More info and tests?

### ISSUE THREAD

**Issue by spacether** [Fatal1ty/mashumaro#102]
**Is your feature request related to a problem? Please describe.**
- What json schema draft is supported? 
- Do you run the json schema test suite verifying support for many of the use cases? 

**Describe the solution you'd like**
Please describe which draft you support in your readme
Please add tests that use the https://github.com/json-schema-org/JSON-Schema-Test-Suite

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by Fatal1ty** [comment]
> Please describe which draft you support in your readme

It's already written there. There is support for Draft 2022-12 and OpenAPI 3.1.

> Please add tests that use the https://github.com/json-schema-org/JSON-Schema-Test-Suite

Thank you for the link! As far as I understand, these tests are for JSON Schema validators which mashumaro is not currently yet. You can build JSON Schema for Python types but not vice versa. Validation of the data by JSON Schema will be implemented in the foreseeable future, I hope.

**Comment by spacether** [comment]
Thanks for explaining that.
How about listing the supported draft closer to the top.
How about listing there that json schema keywords x y z constraints are not enforced and that this library does not run validation.

**Comment by Fatal1ty** [comment]
> How about listing there that json schema keywords x y z constraints are not enforced and that this library does not run validation?

I don't think this is necessary at this stage because all the constraints are currently located in separate `mashumaro.jsonschema.annotations` subpackage which is used only for JSON Schema generation. I'm planning to move them to `mashumaro.core` or somewhere else when they will be not just annotations but instructions for validation which will be performed during deserialization.

> How about listing the supported draft closer to the top.

I will reorganize README when JSON Schema constraints will be used not only for generation but also for validation. For now, I think, it is enough that there is a word "generation" in the key features at the top.

**Comment by Fatal1ty** [comment]
@spacether it there something else or we can close this issue?
