### ISSUE TITLE
Performance of json_schema generation

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#137]
**Is your feature request related to a problem? Please describe.**
I got everything to work in our schema generation with 3.9. Thanks for that! But the performance was substantially worse (2x slower) than with our current schema generation (https://github.com/dbt-labs/hologram/).  That app caches the fields and the schemas, so I assume that's what is causing the difference.

**Describe the solution you'd like**
Similar caching of fields (?) and schemas.

**Describe alternatives you've considered**
I could try to pull out the schema caching code from hologram and pull it into our own app and see if that addresses the problem. Could also try pre-generating the schemas and storing them statically.

**Comment by Fatal1ty** [comment]
Hi @gshank 

> But the performance was substantially worse (2x slower)

How did you measure performance? You were running your [`json_schema`](https://github.com/dbt-labs/dbt-core/blob/21210bd1cf38f52a9a8a9731ce06b503dfeb9975/core/dbt/dataclass_schema.py#L74-L78) method for the same dataclass sequentially, right? If this is the case, then you can simply cache the result once, since it will not change. The easiest way with `lru_cache`:

```python
from functools import lru_cache

def foo():
    print('run foo!')
    return 42

class Bar:
    @classmethod
    @lru_cache(maxsize=1)
    def json_schema(cls):
        return foo()

print(Bar.json_schema())
print(Bar.json_schema())

# run foo!
# 42
# 42
```

I see hologram uses a class-level cache when you apply JsonSchemaMixin to the class. This is a wise decision but it will make it impossible to use the same dataclass in multiple root dataclasses with overriden serialization.

**Comment by gshank** [comment]
This might work if we had a json_schema method on every class, but the json_schema method is on a base class and so we don't get the right json_schema.

**Comment by Fatal1ty** [comment]
@gshank to make `lru_cache` work for unknown number of subclasses I can suggest you set `max_size=None` since it's limited to 128 by default.

**Comment by Fatal1ty** [comment]
@gshank looks like you’ve sorted out the caching problem? Can we close this issue?

**Comment by Fatal1ty** [comment]
I’m going to close this issue as stale. Feel free to reopen it if needed.
