### ISSUE TITLE
Can immutable dataclasses be hashed as dictionary keys?

### ISSUE THREAD

**Issue by user293811** [Fatal1ty/mashumaro#160]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to hash (immutable) dataclass objects as keys. Currently I have a field which contains a dict for which the keys are a dataclass object.  I get the following error:
```
mashumaro.exceptions.UnserializableDataError: dict with dataclasses as keys is not supported by mashumaro
```
I tried subclassing NamedTuple and got: 
```
mashumaro.exceptions.UnserializableDataError: ForwardRef('str') as a field type is not supported by mashumaro
```

**Describe the solution you'd like**
Would be great if I could have immutable dataclasses as keys. 

**Describe alternatives you've considered**
Tried named tuples, which did not work. 

**Additional context**
This is my intended usecase:
```py
@dataclass
class NetworkConfig(DataClassYAMLMixin):
    network: dict[NodeIdentifier, NodeConfig]

@dataclass(frozen=True, eq=True)
class NodeIdentifier(DataClassYAMLMixin):
    group: str
    name: str

@dataclass
class NodeConfig:
    name: str
    family: str 
    subscribers: list[NodeIdentifier] = field(default_factory=list)
```

**Comment by Fatal1ty** [comment]
Hi @user293811 

> ```
> mashumaro.exceptions.UnserializableDataError: dict with dataclasses as keys is not supported by mashumaro
> ```

Let me explain why you see this exception. All the supported serialization formats (json, msgpack, yaml, toml) are kind of dictionary based and allow only simple immutable types to be keys. By default dataclasses are serialized into dicts which can't be dictionary keys because they are mutable. NamedTuples are serialized into lists or dicts depending on the engine you choose (default is lists), so they can't be dictionary keys too.

Taking all above into account, if you want to use dataclasses or named tuples as keys in your structure, you should provide a custom serialization (and deserialization for the reverse) method that will convert them into simple immutable object like string. As you have noticed, SerializableType is one of the available approaches to providing a custom serialization method. However, in the current implementation of mappings serialization there is still a code checking that the key is not a dataclass:
https://github.com/Fatal1ty/mashumaro/blob/92d539cfde20c50d953730128441b951f60505cd/mashumaro/core/meta/types/common.py#L138-L147

This is why you were forced to remove the dataclass decorator. To workaround this problem we can extend this condition by checking SerializableType subclassing. Serialization will fail with `TypeError: unhashable type: 'xxx'` if dataclass is intentionally converted to unhashable type,  but I think we can leave it.

The proposed fix looks trivial. I can do it but if you're willing to contribute yourself, PR is welcome.

**Comment by Fatal1ty** [comment]
> I tried subclassing NamedTuple and got:
> 
> ```
> mashumaro.exceptions.UnserializableDataError: ForwardRef('str') as a field type is not supported by mashumaro
> ```

This looks like another problem related to ForwardRef support. I managed to support forward references to TypedDicts [here](https://github.com/Fatal1ty/mashumaro/issues/144) but this is something new. Could you provide a reproducible example with details in a separate issue? I'd like to cover as many cases as possible.

**Comment by Fatal1ty** [comment]
I modified the process of checking to check if the key type is Hashable. This alteration will also trigger an `UnserializableField` exception for other types that are not hashable.

If you remove `frozen=True` parameter from `NodeIdentifier` the following exception will now be raised:
```python
mashumaro.exceptions.UnserializableField: Field "network" of type dict[NodeIdentifier, NodeConfig] in NetworkConfig is not serializable: NodeIdentifier is unhashable and can not be used as a key
```
