### ISSUE TITLE
Using Union with int/float casts to whichever appears first

### ISSUE THREAD

**Issue by ggydush** [Fatal1ty/mashumaro#190]
* mashumaro version: 3.11
* Python version: 3.11.5
* Operating System: MacOS

### Description

Using a dataclass with Union comprised of int/float causes the value to be cast to whichever appears first in the Union definition. Looking at the pack_union [method](https://github.com/Fatal1ty/mashumaro/blob/fafe769da3e83f67bed487127e03198069066a56/mashumaro/core/meta/types/pack.py#L281), the output makes sense, but wondering if special cases should be added to preserve int/float types.

### What I Did

```python
from dataclasses import dataclass

from mashumaro.mixins.json import DataClassJSONMixin


@dataclass
class Example(DataClassJSONMixin):
    val1: float | int
    val2: int | float


print(Example(val1=3, val2=3.5).to_dict())
```
Output:
```console
{'val1': 3.0, 'val2': 3}
```

**Comment by Fatal1ty** [comment]
Default converters for `int` and `float` types on serialization are `int` and `float` functions respectively. It has its roots in how `Union` types are currently processed. Imagine that you have `Union[int, <another_dataclass>]`. If `int` values were passing as is, then we would be passing `<another_dataclass>` values as is because "passing through" strategy appears first. I have plans to rework `Union` types and get rid of explicit converters for `int`, `float` types but before that you can use [`pass_through`](https://github.com/Fatal1ty/mashumaro#passing-field-values-as-is) helper:
```python
from dataclasses import dataclass

from mashumaro import pass_through
from mashumaro.config import BaseConfig
from mashumaro.mixins.json import DataClassJSONMixin


@dataclass
class Example(DataClassJSONMixin):
    val1: float | int
    val2: int | float

    class Config(BaseConfig):
        serialization_strategy = {
            int: {"serialize": pass_through},
            float: {"serialize": pass_through},
        }


print(Example(val1=3, val2=3.5).to_dict())
```

**Comment by ggydush** [comment]
That makes total sense, and the Config overrides should work fine for my use case! Thanks for the prompt response and providing a solution!

**Comment by Fatal1ty** [comment]
@ggydush you might be interested in this pull request:
* https://github.com/Fatal1ty/mashumaro/pull/194
