### ISSUE TITLE
What changed in 3.15?

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#268]
We had to pin our code to < 3.15 because a number of things broke with the upgrade. I don't actually think (so far) that it's a problem with mashumaro, it actually looks like it mostly fixed bugs. The handful of things that I know broke:
1) A field defined Union[str, float] actually also allowed ints, but it didn't serialize correctly so we left out the int (which oddly worked <3.15 but broke with 3.15). With 3.15 the Union[int, float, str] works okay. 
2) A bool field with an invalid string value in a dictionary, got converted to True when deserialized with "from_dict" so the validation which was done after the from_dict got lost. I've refactored the code to validate before performing a "from_dict". 
3) A field defined as Optional[List[str], List[SomeObject]] which was set to List[SomeObject] got serialized to List[str]. I reordered this to have the List[str] after the List[SomeObject] but haven't yet verified that it works.

I've looked through the code changes, but it's not clear to me what drove these changes. I'm asking because I want to know if I should be going through our Unions and changing the order to put string things last.

Thanks,
Gerda Shank
dbt Labs

**Comment by Fatal1ty** [comment]
Hello @gshank 

> 1. A field defined Union[str, float] actually also allowed ints, but it didn't serialize correctly so we left out the int (which oddly worked <3.15 but broke with 3.15). With 3.15 the Union[int, float, str] works okay.

There were no changes in `Union` serialization in 3.15. They were in 3.13 in [this](https://github.com/Fatal1ty/mashumaro/pull/194) PR. Before 3.13 the order of basic types (`int`, `float`, `str`, `bool`) in `Union` variants had impact on serialization. Since 3.13 this test shows no difference in the order: https://github.com/Fatal1ty/mashumaro/blob/19d4642d0868cc01dde1b133c2ca243484fa9196/tests/test_union.py#L136-L141

> 2\. A bool field with an invalid string value in a dictionary, got converted to True when deserialized with "from_dict" so the validation which was done after the from_dict got lost. I've refactored the code to validate before performing a "from_dict".

To be fair, there was no such validation. Most likely, you encountered the same problem as [this](https://github.com/Fatal1ty/mashumaro/issues/42) when any value was passed through as is for the expected field of type `bool`. In 3.15 it was fixed in order to guarantee that the expected `bool` value will be of type `bool` in the end by wrapping it with `bool(...)`. However, if you expect `bool` inside `Union`, it will be converted only if the input value was a value that does not correspond to all variants and `bool` is to the left of others. You can see all test cases here: https://github.com/Fatal1ty/mashumaro/blob/19d4642d0868cc01dde1b133c2ca243484fa9196/tests/test_union.py#L20-L110

> 3\. A field defined as Optional[List[str], List[SomeObject]] which was set to List[SomeObject] got serialized to List[str]. I reordered this to have the List[str] after the List[SomeObject] but haven't yet verified that it works.

I believe you mean `Union[List[str], List[SomeObject]]` here because `Optional[List[str], List[SomeObject]]` is invalid syntax. Again, `Union` serialization was changed in 3.13 and it only concerned basic types, which `List[str]` and `List[SomeObject` are not. Instead of reordering you can write it as `List[Union[str, SomeObject]]`. This form is shorter and allows any order — `str, SomeObject` or `SomeObject, str`.

**Comment by gshank** [comment]
Yes, you're correct that I mean `Union[List[str], List[SomeObject]]`.  You addressed the issue with 3 in the other ticket I opened. I will try the workaround for that.

Thanks
