### ISSUE TITLE
to_dict() fails for dictionaries with tuple keys

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#49]
We have some dictionaries which have tuple keys. 'from_dict' works okay with a pre-constructed dictionary, but to_dict() fails with the error: TypeError: unhashable type: 'list'

`#!/usr/bin/env python
from typing import Union, Tuple, Dict
from dataclasses import dataclass
from mashumaro import DataClassDictMixin
from mashumaro.types import SerializableType

@dataclass                                                               
class TestClass(DataClassDictMixin):                                              
    name: str                                  
    patches: Dict[Tuple[str, str], str]

dct = {
    'name': 'testing',
    'patches': {
        ('one', 'name'): 'test1',
        ('two', 'order'): 'test2',
        ('three', 'change'): 'test3',
    }
}

obj = TestClass.from_dict(dct)
print(obj)

new_dct = obj.to_dict()
print(new_dct)

`

**Comment by Fatal1ty** [comment]
Using a `tuple` as a key is not supported out of the box because using sequences as a key is not suitable for msgpack, yaml, json, and other serialization formats that accept simple types as keys. `mashumaro` serializes all sequences into a single form — `list` which is unhashable type.  If you really don't need to deal with something but a dictionary in the end, you have various workarounds here:
* use your own `SerializableType` for dictionary keys
* use something like `lambda x: x` in [`serialize`](https://github.com/Fatal1ty/mashumaro#serialize-option) option
* register a serialization method for `Tuple[str, str]` globally using `serialization_strategy` config option:
```python
@dataclass
class TestClass(DataClassDictMixin):
    name: str
    patches: Dict[Tuple[str, str], str]

    class Config(BaseConfig):
        serialization_strategy = {
            Tuple[str, str]: {
                'serialize': lambda x: x
            }
        }
```

**Comment by gshank** [comment]
Thanks for the update. That makes sense that the serialization formats don't support tuple keys. I'll either switch to using a different kind of key or one of the strategies that you mentioned.
