### ISSUE TITLE
Partially serialize objects

### ISSUE THREAD

**Issue by vdperera** [Fatal1ty/mashumaro#82]
This is not really an issue but more of a feature request (or maybe this already exist and I haven't figured out how to do it). In short is it possible partially serialize an object (i.e., select some of the attributes to be ignored)? This is my use case:
```
@dataclass
class Person():
    first_name: str
    last_name: str
    dob: datetime.date
    age: int
```
In my code I'll often access age so I'd like to have it as an attribute but I don't want to serialize it as (1) it can be computed from dob and therefore is redundant, (2) it might change in the future (e.g., if i need to compute the age with respect to a different date). I'd like to specify that age doesn't need to be serialized and to compute it in my `__post_init__` when deserializing an object.

**Comment by Fatal1ty** [comment]
If you need the "age" to be an attribute not a property, you can use the [hook](https://github.com/Fatal1ty/mashumaro#after-serialization) to cut "age" out from the final dict:
```python
@dataclass
class Person(DataClassDictMixin):
    first_name: str
    last_name: str
    dob: datetime.date
    age: int = field(init=False)

    def __post_init__(self):
        self.age = (datetime.date.today() - self.dob).days // 365

    def __post_serialize__(self, d):
        d.pop("age")
        return d
```

But there is a sticky moment here. If you pass the final dict back to `Person.from_dict` you will get an error:
```python
mashumaro.exceptions.MissingField: Field "age" of type int is missing in Person instance
```
This will happen because we unintentionally don't take into account `init=False`. I think we need to consider skipping such fields at least during deserialization.

**Comment by vittorio-perera** [comment]
So it looks like what I am looking for is not currently supported as my final goal is to also dump to and load from json (hence I'll run into the `from_dict` issue). I was able to identify the attributes that need to be skipped using:
```

**Comment by Fatal1ty** [comment]
The fix will be pretty simple. I sketched out a solution [here](https://github.com/Fatal1ty/mashumaro/compare/master...skip-init-false). I'll find time to make a couple of tests and release it soon.

**Comment by vittorio-perera** [comment]
Awesome, thanks!

**Comment by Fatal1ty** [comment]
So, the fix in the master. You can give it a try :)

**Comment by Fatal1ty** [comment]
So, the fix is in the master. You can give it a try :)

**Comment by vittorio-perera** [comment]
👍  Will try asap!

**Comment by vittorio-perera** [comment]
@Fatal1ty, was able to test this only today and seems to work beautifully. Any chance it can make it to a release?

**Comment by Fatal1ty** [comment]
@vittorio-perera, thank you for testing. I'll make a release in a couple of days.

**Comment by Fatal1ty** [comment]
Release [3.0.4](https://github.com/Fatal1ty/mashumaro/releases/tag/v3.0.4) is ready 🎉

**Comment by mishamsk** [comment]
@Fatal1ty I know this one is closed, however wanted to bring up a case where using post-serialization hook is not an option. Let me know if you'll consider a PR or adding a feature to add a config option to skip attribute serialization - I'll create a PR/issue then.

Consider a case of a tree that has a parent attribute:
```python
@dataclass
class Node:
    parent: Node | None = None
    children: list[Node] = field(default_factory=list)
```

using post-serialization hook is not an option, since for any parent-child pair, it will fail to serialize (will loop forever). We could probably use `pass_though` and then pop in post-serialization, but making a new option or a serialization sentinel akin to `pass_though`, say `skip` would be better IMHO.

In my real-life scenario parent is init=false and only assigned after the whole tree has been built (simply descending recursively from the root), so skipping it is a good simple solution.

**Comment by Fatal1ty** [comment]
I forgot to say that since version 3.7 there is now "omit" option:
```python
import datetime
from dataclasses import dataclass, field
from mashumaro import DataClassDictMixin

@dataclass
class Person(DataClassDictMixin):
    first_name: str
    last_name: str
    dob: datetime.date
    age: int = field(metadata={"serialize": "omit"})


person = Person("John", "Doe", datetime.date(2000, 1, 1), 23)
assert person.to_dict() == {"first_name": "John", "last_name": "Doe", "dob": "2000-01-01"}
```

**Comment by mishamsk** [comment]
@Fatal1ty yep, seen that and already using it. Thanks a lot. I still struggling to find time to publish my library though as we dicssued in other thread...

**Comment by Fatal1ty** [comment]
> I still struggling to find time to publish my library though as we dicssued in other thread...

Sounds familiar, I've been keeping some ideas in my head for months. Great things take time and effort :)
