### ISSUE TITLE
Support classes that inherit both mixin & serializabletype

### ISSUE THREAD

**Issue by mishamsk** [Fatal1ty/mashumaro#92]
**Is your feature request related to a problem? Please describe.**

I am using a pattern where I have an abstract class which inherits from SerializableType and one (but not all) of it's subclasses is a dataclass with mashumaro mixin. The abstract class's _serialize/_deserialize methods throw NotImplemented because they are, well, abstract.

The problem is when you use the subclass that is also a dataclass with a mixin as type for some downstream dataclass. CodeBuilder ignores the fact that subclass has generated to_dict/from_dict and instead treats it as SerializableType subclass and generates a call to _serialize/_deserialize which are not implemented.

**Describe the solution you'd like**
I would argue that having mixin in the inheritance chain should take precedence over SerializableType and thus treat a class accordingly.

**Describe alternatives you've considered**
There are many ways to workaround it obviously:
* Check if to_dict/from_dict exist within the abstract base class _serialize/_deserialize methods and call them if they do
* Implement _serialize/_deserialize on all subclasses that would call to_dict/from_dict

**Additional context**
Here is a sample code that illustrates the behavior
```python
from __future__ import annotations
from typing import Any
from mashumaro.mixins.json import DataClassJSONMixin
from mashumaro.types import SerializableType
from dataclasses import dataclass


class Foo(SerializableType):
    def _serialize(self) -> dict[str, Any]:
        raise NotImplementedError

    @classmethod
    def _deserialize(cls, value: dict[str, Any]) -> Foo:
        raise NotImplementedError


@dataclass
class Bar(DataClassJSONMixin, Foo):  # Inheritance order doesn't matter
    f: str


@dataclass
class Baz(DataClassJSONMixin):
    bar: Bar


print(Baz(Bar("f")).to_dict())  # Raises NotImplementedError, because Foo._serialize is called
```

**Comment by mishamsk** [comment]
actually, no, scratch that. Turns out it is even better that it works as it is now, cause I've been able to support arbitrary subclass serialization this way. Check below, maybe worth making it an opt-in feature (although `globals()` will have to be replaced by a registry of subclasses that has to be tracked for this to work across modules - something I use in my real code).

Just to explain the use case - I built a custom AST library, which we use in a project. AST nodes (sub-trees) can have arbitrary children which are all subclasses of the same base node => to (de)serialize one needs to track the actual type of the node. Mashumaro beats pydantic, marshmallow, cattrs here, cause neither of them would allow a meaningful (or at least such an easy and still performant) solution.

```python
from __future__ import annotations
import typing as t
from mashumaro.mixins.json import DataClassJSONMixin
from mashumaro.types import SerializableType
from dataclasses import dataclass


@dataclass
class Base(DataClassJSONMixin, SerializableType):
    base_f: str

    def _serialize(self) -> t.Dict[str, t.Any]:
        out = {"class": self.__class__.__name__}

        out.update(self.to_dict())

        return out

    @classmethod
    def _deserialize(cls, value: t.Dict[str, t.Any]) -> Base:
        class_name = value.pop("class", None)

        if class_name is None:
            raise ValueError("Missing class name ('class' field) in source")

        clazz = globals().get(class_name, None)
        if clazz is None or not issubclass(clazz, Base):
            raise ValueError(f"Unknown Base class name: {class_name}")

        return clazz.from_dict(value)


@dataclass
class Sub(Base):
    sub_f: str


@dataclass
class Container(DataClassJSONMixin):
    children: list[Base]


base = Base("base")
sub = Sub("sub", "sub")
c = Container(children=[base, sub])
assert c == Container.from_dict(c.to_dict())
```

**Comment by Fatal1ty** [comment]
Hi @mishamsk 

I'm glad that you found mashumaro the most suitable for your task!

Let me just explain why you get `NotImplementedError` in the first message's example. Priority of `SerializableType` methods over `DataClassDictMixin` methods is here for a reason. As you noticed you can call `to_dict` / `from_dict` inside `_serialize` / `_deserialize` methods. But you can't do the opposite. Actually, you could tell CodeBuilder to generate code for `to_*` / `from_*` methods so that `_serialize` / `_deserialize` methods would be called for `Foo` class but it has to be done in a class that would depend on `Foo` class e.g. using `serialization_strategy` inside a dependent's `Config`. Anyway, it's not the same thing. If you can make any class serializable using `SerializableType`, why not allow it for classes that inherit `DataClassDictMixin`?

As for using a base class and handle all its subclasses, you're actually dealing with discriminated unions. I think about it periodically and haven't come up with a good design solution. There are many different ways to do it and one of them you just discovered with `SerializableType`. The last time I was thinking about using `Annotated` generic for different things (constraints, 
```python
class Discriminator:
    def __init__(
        self,
        key: str,
        class_name_as_value: bool = True,
    ):
        self._key = key
        self._class_name_as_value = class_name_as_value

@dataclass
class Base(DataClassJSONMixin):
    base_f: str

@dataclass
class Sub(Base):
    sub_f: str

@dataclass
class Container(DataClassJSONMixin):
    children: list[t.Annotated[Base, Discriminator("_type")]]

base = Base("base")
sub = Sub("sub", "sub")
c = Container(children=[base, sub])
print(c.to_dict())
# {
#     'children': [
#         {'_type': 'Base', 'base_f': 'base'},
#         {'_type': 'Sub', 'base_f': 'sub', 'sub_f': 'sub'}
#     ]
# }
```

It seems like an elegant solution but I'm still not sure if it's the best one. What do you think?

**Comment by Fatal1ty** [comment]
Hi @mishamsk 

I'm glad that you found mashumaro the most suitable for your task!

Let me just explain why you get `NotImplementedError` in the first message's example. Priority of `SerializableType` methods over `DataClassDictMixin` methods is here for a reason. As you noticed you can call `to_dict` / `from_dict` inside `_serialize` / `_deserialize` methods. But you can't do the opposite. Actually, you could tell CodeBuilder to generate code for `to_*` / `from_*` methods so that `_serialize` / `_deserialize` methods would be called for `Foo` class but it has to be done in a class that would depend on `Foo` class e.g. using `serialization_strategy` inside a dependent's `Config`. Anyway, it's not the same thing. If you can make any class serializable using `SerializableType`, why not allow it for classes that inherit `DataClassDictMixin`?

As for using a base class and handle all its subclasses, you're actually dealing with discriminated unions. I think about it periodically and haven't come up with a good design solution. There are many different ways to do it and one of them you just discovered with `SerializableType`. The last time I was thinking about using `Annotated`:
```python
class Discriminator:
    def __init__(
        self,
        key: str,
        class_name_as_value: bool = True,
    ):
        self._key = key
        self._class_name_as_value = class_name_as_value

@dataclass
class Base(DataClassJSONMixin):
    base_f: str

@dataclass
class Sub(Base):
    sub_f: str

@dataclass
class Container(DataClassJSONMixin):
    children: list[t.Annotated[Base, Discriminator("_type")]]

base = Base("base")
sub = Sub("sub", "sub")
c = Container(children=[base, sub])
print(c.to_dict())
# {
#     'children': [
#         {'_type': 'Base', 'base_f': 'base'},
#         {'_type': 'Sub', 'base_f': 'sub', 'sub_f': 'sub'}
#     ]
# }
```

It seems like an elegant solution but I'm still not sure if it's the best one. What do you think?

**Comment by mishamsk** [comment]
I guess it really depends on what’s your goal / how you perceive mashumaro. If you think about it as an interoperability lib, directly competing with pydantic etc., then a more generic feature (like creating discriminator logic) would make sense, since you can’t count on the “other side” (whoever produces serialized input that mashumaro deserializes) conforming to some mashumaro standard.

However, I see mashumaro as a great “private” (de)serialization solution. Means:
* I care about being able to quickly (de)serialize my models, using different formats (e.g. I use json for parser tests, but will use msgpack for other uses)
* I care about flexibility of (de)serialisation logic
* I do not have to bother with validation, since only my will produce and consume the output

So this is very different from pydantic. Much closer to pickle I guess. To illustrate further - we are using pydantic too in a different place where we mostly need validation and precise error reporting, but do not do (de)serialization.

For my case, a design that “just” works makes more sense. Having to mess with Annotated and Discriminators does not. The logic that I’ve implemented can be easily embedded in the lib itself, since you already use __init_subclass__, you can track all subclasses for Mixins & SerializableTypes and then it will “just work”. E.g. you can add a config option, smth like `serialized_type_field` which is None by default. If it is set, then it will be used to capture the type.

Last, but not the least - fighting pydantic for popularity is probably futile. Even being the library used by dbt;-)  Especially now that pydantic V2 will be rust => performance will not be a differentiator anymore. But making something different is another story.

**Comment by Fatal1ty** [comment]
I’m closing this issue since the original problem was solved. For those who are looking for more examples of using a base class as an annotation for deserialization of child classes, the following issue might help:
* https://github.com/Fatal1ty/mashumaro/issues/67
